"""
Create summary plots comparing original and optimized model parameters.

This script reads CSV files generated by messy_middle_analysis.py and creates
comparison plots showing:
- Data as markers with error bars
- Original model as unfilled bars
- Optimized model as unfilled bars with different color

Usage:
    python source/make_summary_plots.py
"""

import pandas as pd
import matplotlib.pyplot as plt
import numpy as np
from pathlib import Path

# Truck names to process
TRUCK_NAMES = ['saia2', '4gen', 'joyride', 'nevoya_with_weight']

# Display titles for plots
TRUCK_TITLES = {
    'saia2': 'Saia',
    '4gen': '4Gen',
    'joyride': 'Joyride',
    'nevoya_with_weight': 'Nevoya',
}

# Directory containing results
RESULTS_DIR = Path('plots_messy')
OUTPUT_DIR = Path('plots_messy')


def plot_truck_comparison(truck_name, original_df, optimized_df):
    """
    Create comparison plot for a single truck showing original vs optimized parameters.
    
    Parameters:
    -----------
    truck_name : str
        Name of the truck
    original_df : pd.DataFrame
        Results with original parameters
    optimized_df : pd.DataFrame
        Results with optimized parameters
    """
    fig, ax1 = plt.subplots(1, 1, figsize=(12, 6))
    
    # Sort by event number
    original_df = original_df.sort_values('event')
    optimized_df = optimized_df.sort_values('event')
    
    # Get event numbers as strings for x-axis
    events = original_df['event'].astype(str).tolist()
    x_pos = np.arange(len(events))
    bar_width = 0.35
    
    # --- Fuel Economy Panel ---
    # Plot model results as unfilled bars
    ax1.bar(x_pos - bar_width/2, original_df['model_fuel'], 
            width=bar_width, alpha=0.3, edgecolor='C0', 
            facecolor='none', linewidth=2, label='Model (Original)')
    ax1.bar(x_pos + bar_width/2, optimized_df['model_fuel'], 
            width=bar_width, alpha=0.3, edgecolor='C1', 
            facecolor='none', linewidth=2, label='Model (Calibrated)')
    
    # Plot data as markers with error bars
    # Convert percentage uncertainties to absolute values
    fuel_errors = original_df['data_fuel'] * original_df['fuel_unc_pct'] / 100
    ax1.errorbar(x_pos, original_df['data_fuel'], yerr=fuel_errors,
                 fmt='o', color='black', markersize=16, capsize=10, 
                 linewidth=2, label='Data', zorder=10)
    
    truck_title = TRUCK_TITLES.get(truck_name, truck_name)
    ax1.set_ylabel('Fuel Economy (kWh/mile)', fontsize=24)
    ax1.set_title(f'{truck_title}', fontsize=28, fontweight='bold')
    ax1.set_xticks(x_pos)
    ax1.set_xticklabels(events, fontsize=18)
    ax1.set_xlabel('Driving Event', fontsize=24)
    ax1.legend(loc='lower left', bbox_to_anchor=(0, 1.02, 1, 0.2),
               ncol=2, mode='expand', borderaxespad=0, fontsize=24, frameon=False)
    ax1.grid(axis='y', alpha=0.3)
    ax1.tick_params(axis='y', labelsize=18)
    
    plt.tight_layout()
    return fig


def main():
    """Main function to generate all summary plots."""
    print("Generating summary comparison plots...")
    
    for truck_name in TRUCK_NAMES:
        print(f"\nProcessing {truck_name}...")
        
        # Load CSV files
        original_path = RESULTS_DIR / f"{truck_name}_results_original.csv"
        optimized_path = RESULTS_DIR / f"{truck_name}_results_optimized.csv"
        
        if not original_path.exists():
            print(f"  Warning: {original_path} not found, skipping...")
            continue
        if not optimized_path.exists():
            print(f"  Warning: {optimized_path} not found, skipping...")
            continue
        
        original_df = pd.read_csv(original_path)
        optimized_df = pd.read_csv(optimized_path)
        
        # Create comparison plot
        fig = plot_truck_comparison(truck_name, original_df, optimized_df)
        
        # Save plot
        output_path = OUTPUT_DIR / f"{truck_name}_summary_comparison.png"
        fig.savefig(output_path, dpi=300, bbox_inches='tight')
        print(f"  Saved: {output_path}")
        plt.close(fig)
    
    print("\nDone!")


if __name__ == "__main__":
    main()
